export enum RoutesConst {
  OPERATIONS = 'operations',
  ORGANIZATIONS = 'organizations',
  ORGANIZATION = 'organization',
  CONTRAGENTS = 'contragents',
  CONTRAGENT = 'contragent',
  ACCOUNTS = 'accounts',
  ACCOUNT = 'account',
  ARTICLES = 'articles',
  ARTICLE = 'article',
  CASES = 'cases',
  CASE = 'case',
  DEALS = 'deals',
  DEAL = 'deal',
  IMPORTS = 'imports',
  IMPORT = 'import',
  SUMMARY = 'summary',
  STANDARTS = 'standarts',
  STANDART = 'standart',
  REPORT = 'report',
}
