export enum RoutesConst {
	OPERATIONS = 'operations',
	ORGANIZATIONS = 'organizations',
	ORGANIZATION = 'organization',
	COUNTERPARTIES = 'counterparties',
	COUNTERPARTY = 'counterparty',
	ACCOUNTS = 'accounts',
	ACCOUNT = 'account',
	ARTICLES = 'articles',
	ARTICLE = 'article',
	CASES = 'cases',
	CASE = 'case',
	TRANSACTIONS = 'transactions',
	TRANSACTION = 'transaction',
	IMPORTS = 'imports',
	IMPORT = 'import',
	SUMMARY = 'summary',
}
